# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1854b40aa73f2890e2266889086579579ab7402f6d841e81837c6fd162153bcca8eaaa333c26c2a06f7cb6f84a5d3b4100eae59aad197f14ce49a99b98442106

test:
  secret_key_base: 82e7e016900bc5c2c1797021ff3fe2db69ce25e4cadebc757d86d09a8f9d6123838e9afdf8d4b5ee26f06304359ef9be23d9c035fc7cde4078b9414ada2021b6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
